### PR TITLE
Update to stm32-rs head, adds L5 GPIO enums

### PR DESCRIPTION
**Pull request by kenbell**

### CODE REVIEW

**Comment by kenbell** [comment]
@aykevl @deadprogram is it possible to merge this change?  Will (hopefully) let me fix-up the L5 patch, the stm32-rs PR has been merged: https://github.com/stm32-rs/stm32-rs/pull/479

**Comment by deadprogram** [comment]
LGTM. @aykevl any reason to not merge?

**Comment by aykevl** [comment]
It looks like the files svd/stm32l552.svd and svd/stm32l562.svd are not exactly based on upstream stm32-rs. It looks related to https://github.com/stm32-rs/stm32-rs/pull/479#pullrequestreview-572476648?
Can you update the PR with this change?

Other than that, looks good to me.

**Comment by kenbell** [comment]
Sorry about that - i did indeed miss some changes.  I've pushed another change that should bring everything up to date with change e75d42f in stm32-rs

I've done a smoketest on tinygo with these changes (AVR=0 XTENSA=0)

**Comment by aykevl** [comment]
Thank you!

**Pull request merged**
